### ISSUE TITLE
Area default is not included in the deployment , but the interface always displays default

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper-labs/kubeclipper#111]
**Describe the Bug**
Area default is not included in the deployment, but the interface always displays default
so that the node cannot be seen
![region](https://user-images.githubusercontent.com/100403985/184572011-68a9dcc1-7eed-492f-b76e-fc7eb082cd9a.png)

**Comment by x893675** [comment]
@moweiwei 
/area console
