### ISSUE TITLE
Node role label remain after deleting the cluster

### ISSUE THREAD

**Issue by Metrora** [kubeclipper-labs/kubeclipper#149]
**Describe the Bug**

Node role labels remain after deleting the cluster.

**Versions Used**

Kubeclipper: master branch

**Environment**

macos , local debug

**How To Reproduce**

1. Create a cluster by kubeclipper
2. Delete the cluster
3. Go to the node list page 
4. Find the node is still with role 'master' or 'worker'

**Expected behavior**

Nodes role label is empty

**Comment by simonyangcj** [comment]
@Metrora thx for give it try, we looking into this
