### ISSUE TITLE
did not remove custom kubelet directory when delete cluster

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper-labs/kubeclipper#173]
**Describe the Feature Request**
 cluster delete did not remove custom kubectl directory

**Versions Used**
Kubernetes: v1.23.6
Kubeclipper: master

**Screenshot**
<img width="330" alt="test" src="https://user-images.githubusercontent.com/56632872/187613838-8268518b-8d69-4975-9d19-d3eae4376c92.png">

/kind feature-request

**Comment by lixd** [comment]
maybe it's kubelet data dir, need delete when cluster deleted.

**Comment by x893675** [comment]
/retitle did not remove custom kubelet directory when delete cluster
