### ISSUE TITLE
failed to run install sh on my ubuntu 20.04 version.

### ISSUE THREAD

**Issue by gongysh2004** [kubeclipper-labs/kubeclipper#194]
failed to run install sh on my ubuntu 20.04 version.
`root@compute1:~# cat /etc/issue
Ubuntu 20.04.5 LTS \n \l`

`root@compute1:~# curl -sfL https://oss.kubeclipper.io/kcctl.sh | sh -
sh: 23: [[: not found
sh: 34: [[: not found
[ERROR]  Unsupported architecture`

**Comment by gongysh2004** [comment]
bash works.

`root@compute1:~# ls -l /usr/bin/sh
lrwxrwxrwx 1 root root 4 Sep  1 04:26 /usr/bin/sh -> dash
root@compute1:~# ls -l /usr/bin/dash
-rwxr-xr-x 1 root root 129816 Jul 18  2019 /usr/bin/dash
root@compute1:~# which bash
/usr/bin/bash
root@compute1:~# curl -sfL https://oss.kubeclipper.io/kcctl.sh | bash -`

**Comment by x893675** [comment]
/assign @qinyer 
/kind documentation
need update docs, use `bash` instead of `sh`
