### ISSUE TITLE
When create a backup with the same name, it will prompt that it cannot be created, but the log of this action will be generated.

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper-labs/kubeclipper#25]
**Describe the Bug**
When creating a backup with the same name, it will prompt that it cannot be created, but the log of this action will be generated.
![备份日志](https://user-images.githubusercontent.com/100403985/180151169-39b5465d-8c7a-44a1-a150-d18bed2e91be.png)

![报错](https://user-images.githubusercontent.com/100403985/180154838-8b7ec136-fe4a-47ea-a395-7061550b82d8.png)

**Versions Used**
Kubernetes: master branch
Kubeclipper: master branch

**Environment**

**How To Reproduce**
1. create a backup
2. create a backup with the same name
3. see the operation log

**Expected behavior**
This log should not be generated.

**Comment by qinyer** [comment]
Because the backup name was not correctly passed in, the filtering judgment for the backup with the same name does not take effect.
