### ISSUE TITLE
The simplest deploy of kcctl installation requires entering the local key or password

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper-labs/kubeclipper#6]
**Describe the Bug**
  The simplest deploy of kcctl installation requires entering the local key or password

**Versions Used**
Kubernetes: master branch
Kubeclipper: master branch

**Environment**
CentOS 7.7.1908
masters:  4cpu/16g; 
3 nodes: 4cpu/16g
3 nodes: 4cpu/12g

**How To Reproduce**
<img width="439" alt="kcctl" src="https://user-images.githubusercontent.com/56632872/179147048-7969e042-f726-4c80-be9a-693346cb8db4.png">

**Expected behavior**
  The simplest installation of kcctl only requires kcctl deploy

**Comment by myuanying** [comment]
/kind need-verify
@qinyer

**Comment by lixd** [comment]
association to #122

**Comment by x893675** [comment]
duplicated #122
/close
