### ISSUE TITLE
When login with keyclock ,the redirect page is 404

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper-labs/kubeclipper#89]
**Describe the Bug**
When login with keyclock ,the redirect page is 404
![redirect](https://user-images.githubusercontent.com/100403985/183861689-40c8287a-8dda-45d4-9d66-4c2ef1810128.png)

![404](https://user-images.githubusercontent.com/100403985/183861709-8ae16301-ab7e-4581-b4e9-cf1e15215e9a.png)

the config yaml:
![截屏2022-08-10 17 19 22](https://user-images.githubusercontent.com/100403985/183865707-c09e54a5-ae06-46b7-b6eb-b44e9b3b2c0c.jpg)

**Comment by myuanying** [comment]
/kind need-verify
@x893675

**Comment by x893675** [comment]
change redirectURL format to {kc-console-address}/oatuh2/redirect/{IDP-Name}
@Mengchenchen
